// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default'];
    HelloWorldChild: typeof import('./src/components/HelloWorldChild.vue')['default'];
    HelloWorldTest: typeof import('./src/components/HelloWorldTest.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    Undefined: typeof import('./src/components/index.vue')['default'];
  }
}

export {};
